export const FETCH_QUIZZES = "FETCH_QUIZZES";
export const FETCH_QUIZZES_SUCCESS = "FETCH_QUIZZES_SUCCESS";
export const FETCH_QUIZZES_ERROR = "FETCH_QUIZZES_ERROR";
export const ANSWER_QUIZ = "ANSWER_QUIZ";
export const RESTART_QUIZZES = "RESTART_QUIZZES";
